apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: formance-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - events
  - namespaces
  - pods
  - secrets
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - externaldns.k8s.io
  resources:
  - dnsendpoints
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - authclients
  - auths
  - benthos
  - brokerconsumers
  - brokers
  - brokertopics
  - databases
  - gatewayhttpapis
  - gateways
  - ledgers
  - orchestrations
  - payments
  - reconciliations
  - resourcereferences
  - searches
  - settings
  - stacks
  - stargates
  - versions
  - wallets
  - webhooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - formance.com
  resources:
  - authclients/finalizers
  - auths/finalizers
  - benthos/finalizers
  - benthosstreams/finalizers
  - brokerconsumers/finalizers
  - brokers/finalizers
  - brokertopics/finalizers
  - databases/finalizers
  - gatewayhttpapis/finalizers
  - gateways/finalizers
  - ledgers/finalizers
  - orchestrations/finalizers
  - payments/finalizers
  - reconciliations/finalizers
  - resourcereferences/finalizers
  - searches/finalizers
  - settings/finalizers
  - stacks/finalizers
  - stargates/finalizers
  - versions/finalizers
  - wallets/finalizers
  - webhooks/finalizers
  verbs:
  - update
- apiGroups:
  - formance.com
  resources:
  - authclients/status
  - auths/status
  - benthos/status
  - benthosstreams/status
  - brokerconsumers/status
  - brokers/status
  - brokertopics/status
  - databases/status
  - gatewayhttpapis/status
  - gateways/status
  - ledgers/status
  - orchestrations/status
  - payments/status
  - reconciliations/status
  - resourcereferences/status
  - searches/status
  - settings/status
  - stacks/status
  - stargates/status
  - versions/status
  - wallets/status
  - webhooks/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - formance.com
  resources:
  - benthosstreams
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - create
  - delete
  - deletecollection
  - get
  - list
  - patch
  - update
  - watch
