apiVersion: v1
kind: ServiceAccount
metadata:
  {{- with .Values.operator.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operatorv2
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: operatorv2
  {{- with .Values.operator.serviceAccount.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  name: formance-controller-manager
  namespace: '{{ .Release.Namespace }}'
