---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.19.0
  name: settings.formance.com
spec:
  group: formance.com
  names:
    kind: Settings
    listKind: SettingsList
    plural: settings
    singular: settings
  scope: Cluster
  versions:
  - additionalPrinterColumns:
    - description: Key
      jsonPath: .spec.key
      name: Key
      type: string
    - description: Value
      jsonPath: .spec.value
      name: Value
      type: string
    name: v1beta1
    schema:
      openAPIV3Schema:
        description: "Settings represents a configurable piece of the stacks.\n\nThe
          purpose of this resource is to be able to configure some common settings
          between a set of stacks.\n\nExample :\n```yaml\napiVersion: formance.com/v1beta1\nkind:
          Settings\nmetadata:\n\n\tname: postgres-uri\n\nspec:\n\n\tkey: postgres.ledger.uri\n\tstacks:\n\t-
          stack0\n\tvalue: postgresql://postgresql.formance.svc.cluster.local:5432\n\n```\n\nThis
          example create a setting named `postgres-uri` targeting the stack named
          `stack0` and the service `ledger` (see the key `postgres.ledger.uri`).\n\nTherefore,
          a [Database](#database) created for the stack `stack0` and the service named
          'ledger' will use the uri `postgresql://postgresql.formance.svc.cluster.local:5432`.\n\nSettings
          allow to use wildcards in keys and in stacks list.\n\nFor example, if you
          want to use the same database server for all the modules of a specific stack,
          you can write :\n```yaml\napiVersion: formance.com/v1beta1\nkind: Settings\nmetadata:\n\n\tname:
          postgres-uri\n\nspec:\n\n\tkey: postgres.*.uri # There, we use a wildcard
          to indicate we want to use that setting of all services of the stack `stack0`\n\tstacks:\n\t-
          stack0\n\tvalue: postgresql://postgresql.formance.svc.cluster.local:5432\n\n```\n\nAlso,
          we could use that setting for all of our stacks using :\n```yaml\napiVersion:
          formance.com/v1beta1\nkind: Settings\nmetadata:\n\n\tname: postgres-uri\n\nspec:\n\n\tkey:
          postgres.*.uri # There, we use a wildcard to indicate we want to use that
          setting for all services of all stacks\n\tstacks:\n\t- * # There we select
          all the stacks\n\tvalue: postgresql://postgresql.formance.svc.cluster.local:5432\n\n```\n\nYou
          can also fetch values from secrets or configmaps using `valueFrom`:\n```yaml\napiVersion:
          formance.com/v1beta1\nkind: Settings\nmetadata:\n\n\tname: postgres-uri-from-secret\n\nspec:\n\n\tkey:
          postgres.ledger.uri\n\tstacks:\n\t- stack0\n\tvalueFrom:\n\t  secretKeyRef:\n\t
          \   name: postgres-credentials\n\t    key: connection-string\n\t    optional:
          false\n\n```\n\nOr from a configmap:\n```yaml\napiVersion: formance.com/v1beta1\nkind:
          Settings\nmetadata:\n\n\tname: postgres-uri-from-configmap\n\nspec:\n\n\tkey:
          postgres.ledger.uri\n\tstacks:\n\t- stack0\n\tvalueFrom:\n\t  configMapKeyRef:\n\t
          \   name: postgres-config\n\t    key: uri\n\t    optional: false\n\n```\n\nNote:
          Secrets and configmaps are resolved from the stack's namespace (which has
          the same name as the stack).\nEither `value` or `valueFrom` must be set,
          but not both.\n\nSome settings are really global, while some are used by
          specific module.\n\nRefer to the documentation of each module and resource
          to discover available Settings.\n\n##### Global settings\n###### AWS account\n\nA
          stack can use an AWS account for authentication.\n\nIt can be used to connect
          to any AWS service we could use.\n\nIt includes RDS, OpenSearch and MSK.
          To do so, you can create the following setting:\n```yaml\napiVersion: formance.com/v1beta1\nkind:
          Settings\nmetadata:\n\n\tname: aws-service-account\n\nspec:\n\n\tkey: aws.service-account\n\tstacks:\n\t-
          '*'\n\tvalue: aws-access\n\n```\nThis setting instruct the operator than
          there is somewhere on the cluster a service account named `aws-access`.\n\nSo,
          each time a service has the capability to use AWS, the operator will use
          this service account.\n\nThe service account could look like that :\n```yaml\napiVersion:
          v1\nkind: ServiceAccount\nmetadata:\n\n\tannotations:\n\t  eks.amazonaws.com/role-arn:
          arn:aws:iam::************:role/staging-eu-west-1-hosting-stack-access\n\tlabels:\n\t
          \ formance.com/stack: any\n\tname: aws-access\n\n```\nYou can note two things
          :\n 1. We have an annotation indicating the role arn used to connect to
          AWS. Refer to the AWS documentation to create this role\n 2. We have a label
          `formance.com/stack=any` indicating we are targeting all stacks.\n    Refer
          to the documentation of [ResourceReference](#resourcereference) for further
          information.\n\n###### JSON logging\n\nYou can use the setting `logging.json`
          with the value `true` to configure elligible service to log as json.\nExample:\n```yaml\napiVersion:
          formance.com/v1beta1\nkind: Settings\nmetadata:\n\n\tname: json-logging\n\nspec:\n\n\tkey:
          logging.json\n\tstacks:\n\t- '*'\n\tvalue: \"true\"\n\n```\n\n###### Authentication
          scopes\n\nYou can enable scope verification for modules using the setting
          `auth.<module-name>.check-scopes` or `auth.*.check-scopes` for all modules.\nWhen
          enabled, modules will verify that authenticated requests include the required
          scopes for the requested operation.\n\nExample to enable scope verification
          for all modules:\n```yaml\napiVersion: formance.com/v1beta1\nkind: Settings\nmetadata:\n\n\tname:
          enable-scopes-all\n\nspec:\n\n\tkey: auth.*.check-scopes\n\tstacks:\n\t-
          '*'\n\tvalue: \"true\"\n\n```\n\nExample to enable scope verification only
          for the ledger module:\n```yaml\napiVersion: formance.com/v1beta1\nkind:
          Settings\nmetadata:\n\n\tname: enable-scopes-ledger\n\nspec:\n\n\tkey: auth.ledger.check-scopes\n\tstacks:\n\t-
          production\n\tvalue: \"true\"\n\n```\n\nNote: The `auth.checkScopes` field
          in module specifications takes priority over Settings when specified."
        properties:
          apiVersion:
            description: |-
              APIVersion defines the versioned schema of this representation of an object.
              Servers should convert recognized schemas to the latest internal value, and
              may reject unrecognized values.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
            type: string
          kind:
            description: |-
              Kind is a string value representing the REST resource this object represents.
              Servers may infer this from the endpoint the client submits requests to.
              Cannot be updated.
              In CamelCase.
              More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
            type: string
          metadata:
            type: object
          spec:
            properties:
              key:
                description: The setting Key. See the documentation of each module
                  or [global settings](#global-settings) to discover them.
                type: string
              stacks:
                description: Stacks on which the setting is applied. Can contain `*`
                  to indicate a wildcard.
                items:
                  type: string
                type: array
              value:
                description: |-
                  The value. It must have a specific format following the Key.
                  Either Value or ValueFrom must be set, but not both.
                type: string
              valueFrom:
                description: |-
                  Source for the value. Can be used to reference a secret or configmap key.
                  Either Value or ValueFrom must be set, but not both.
                properties:
                  configMapKeyRef:
                    description: Selects a key of a ConfigMap.
                    properties:
                      key:
                        description: The key to select.
                        type: string
                      name:
                        description: |-
                          Name of the referent.
                          More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        type: string
                      optional:
                        description: Specify whether the ConfigMap or its key must
                          be defined
                        type: boolean
                    required:
                    - key
                    type: object
                    x-kubernetes-map-type: atomic
                  secretKeyRef:
                    description: Selects a key of a Secret.
                    properties:
                      key:
                        description: The key of the secret to select from.  Must be
                          a valid secret key.
                        type: string
                      name:
                        description: |-
                          Name of the referent.
                          More info: https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names
                        type: string
                      optional:
                        description: Specify whether the Secret or its key must be
                          defined
                        type: boolean
                    required:
                    - key
                    type: object
                    x-kubernetes-map-type: atomic
                type: object
                x-kubernetes-validations:
                - message: exactly one of the fields in [secretKeyRef configMapKeyRef]
                    must be set
                  rule: '[has(self.secretKeyRef),has(self.configMapKeyRef)].filter(x,x==true).size()
                    == 1'
            required:
            - key
            type: object
            x-kubernetes-validations:
            - message: exactly one of the fields in [value valueFrom] must be set
              rule: '[has(self.value),has(self.valueFrom)].filter(x,x==true).size()
                == 1'
        type: object
    served: true
    storage: true
    subresources:
      status: {}
